/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { dai } from "./dai.cairo/dai";
export type { l2_dai_teleport_gateway } from "./l2_dai_teleport_gateway.cairo/l2_dai_teleport_gateway";
